[package]
name = "sid_file"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/fazibear/sid_file"
license-file = "LICENSE"
description = "Parser for SID file format used for SID tunes"

[dependencies]
byteorder = "1.5.0"
